/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

//import controller.Controller;

import view.controller.Controller;


/**
 *
 * @author LORA
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        setLibrarian();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemCreateM = new javax.swing.JMenuItem();
        itemFindM = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemAddBook = new javax.swing.JMenuItem();
        itemViewBook = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemCreateLoanNote = new javax.swing.JMenuItem();
        itemViewLoanNote = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovan.setText("jLabel1");

        jMenu1.setText("Član biblioteke");

        itemCreateM.setText("Kreiraj člana");
        itemCreateM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreateMActionPerformed(evt);
            }
        });
        jMenu1.add(itemCreateM);

        itemFindM.setText("Prikaži članove");
        itemFindM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFindMActionPerformed(evt);
            }
        });
        jMenu1.add(itemFindM);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Knjiga");

        itemAddBook.setText("Dodaj knjigu");
        itemAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddBookActionPerformed(evt);
            }
        });
        jMenu2.add(itemAddBook);

        itemViewBook.setText("Prikaži knjige");
        itemViewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemViewBookActionPerformed(evt);
            }
        });
        jMenu2.add(itemViewBook);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pozajmica");

        itemCreateLoanNote.setText("Kreiraj pozajmicu");
        itemCreateLoanNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreateLoanNoteActionPerformed(evt);
            }
        });
        jMenu3.add(itemCreateLoanNote);

        itemViewLoanNote.setText("Prikaži pozajmice");
        itemViewLoanNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemViewLoanNoteActionPerformed(evt);
            }
        });
        jMenu3.add(itemViewLoanNote);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblUlogovan)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lblUlogovan)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCreateMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreateMActionPerformed
        new MemberForm(new ViewMemberForm()).setVisible(true);
       
    }//GEN-LAST:event_itemCreateMActionPerformed

    private void itemFindMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFindMActionPerformed
        new ViewMemberForm().setVisible(true);
    }//GEN-LAST:event_itemFindMActionPerformed

    private void itemAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddBookActionPerformed
        new BookForm(new ViewBookForm()).setVisible(true);
    }//GEN-LAST:event_itemAddBookActionPerformed

    private void itemViewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemViewBookActionPerformed
        new ViewBookForm().setVisible(true);
    }//GEN-LAST:event_itemViewBookActionPerformed

    private void itemCreateLoanNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreateLoanNoteActionPerformed
        new LoanNoteForm(new ViewLoanNoteForm()).setVisible(true);
    }//GEN-LAST:event_itemCreateLoanNoteActionPerformed

    private void itemViewLoanNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemViewLoanNoteActionPerformed
        new ViewLoanNoteForm().setVisible(true);
    }//GEN-LAST:event_itemViewLoanNoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAddBook;
    private javax.swing.JMenuItem itemCreateLoanNote;
    private javax.swing.JMenuItem itemCreateM;
    private javax.swing.JMenuItem itemFindM;
    private javax.swing.JMenuItem itemViewBook;
    private javax.swing.JMenuItem itemViewLoanNote;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblUlogovan;
    // End of variables declaration//GEN-END:variables

    private void setLibrarian() {
        
        lblUlogovan.setText("Ulogovan bibliotekar: "+Controller.getInstance().getCurrentLibrarian());
    }
    
   
}
